### PR TITLE
Change container.Environment to map

### PR DESCRIPTION
**Pull request by carolynvs**
Currently container.Environment is a string array which opens up many possibilities for the variables to be specified incorrectly, such as duplicate keys or improperly formatted entries. Switching to a map (which is also what Brigade v2 uses) ensures that every entry is valid (assuming a valid environment variable name, it doesn't prevent bad
characters in the key name).

It makes it easier for the user to specify variables safely but does remove the ordering aspect that the array provided. However when we remove the possibility of duplicate keys, then the order defined on the container should not matter, as long as the implementation applies the container values last so that they take precedence over values provided from other sources (per the spec).

### CODE REVIEW

**Comment by krancour** [comment]
I vaguely recall that there might have been a reason it was an array... give me a day or two to see if I can remember why.

**Comment by krancour** [comment]
Ok... I can't recall any reason that I might have made it an array to begin with except, possibly, to be more k8s-like. I don't really consider that a goal though, so this LGTM.

**Review by krancour — APPROVED** [review]

**Comment by carolynvs** [comment]
Having `Environment()` as an array let's you mimic a behavior where repeated environment variable names can be defined and you implicitly relying on the OS to give you the correct (last defined) value for a duplicate key. It's kind of why I prefer modeling this as a map, so that no one _can_ rely on that behavior and they have to be explicit about which value they want the job to use.

**Comment by carolynvs** [comment]
@krancour You'll need to merge this, I don't have write access.

**Pull request merged**
